{"level":"error","message":"Authentication error: No authentication token provided","service":"chat-api","stack":"Error: No authentication token provided\n    at auth (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\src\\middleware\\auth.js:10:13)\n    at Layer.handle [as handle_request] (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\index.js:421:3)\n    at next (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-10-04 14:42:53"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"WebSocket server error: listen EADDRINUSE: address already in use :::5000","port":5000,"service":"chat-api","stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\server.js:333:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-10-05 12:12:57"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"WebSocket server error: listen EADDRINUSE: address already in use :::5000","port":5000,"service":"chat-api","stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\server.js:333:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","syscall":"listen","timestamp":"2025-10-05 18:09:30"}
{"$clusterTime":{"clusterTime":{"$timestamp":"7564567465691185211"},"signature":{"hash":"MoJuD1KKYxe3Gpmr5RRoN8eDmug=","keyId":{"high":1754143565,"low":2,"unsigned":false}}},"code":85,"codeName":"IndexOptionsConflict","errorLabelSet":{},"errorResponse":{"$clusterTime":{"clusterTime":{"$timestamp":"7564567465691185211"},"signature":{"hash":"MoJuD1KKYxe3Gpmr5RRoN8eDmug=","keyId":{"high":1754143565,"low":2,"unsigned":false}}},"code":85,"codeName":"IndexOptionsConflict","errmsg":"Index already exists with a different name: conversationId_1_status_1","ok":0,"operationTime":{"$timestamp":"7564567465691185211"}},"level":"error","message":"❌ Erro ao criar índices: Index already exists with a different name: conversationId_1_status_1","ok":0,"operationTime":{"$timestamp":"7564567465691185211"},"service":"chat-api","stack":"MongoServerError: Index already exists with a different name: conversationId_1_status_1\n    at Connection.sendCommand (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\cmap\\connection.js:305:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Connection.command (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\cmap\\connection.js:333:26)\n    at async Server.command (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\sdam\\server.js:171:29)\n    at async CreateIndexesOperation.executeCommand (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\command.js:76:16)\n    at async CreateIndexesOperation.execute (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\indexes.js:122:9)\n    at async tryOperation (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:207:20)\n    at async executeOperation (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:75:16)\n    at async Collection.createIndex (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\collection.js:329:25)\n    at async addPerformanceIndexes (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\scripts\\add-performance-indexes.js:72:5)","timestamp":"2025-10-23 20:45:57"}
{"$clusterTime":{"clusterTime":{"$timestamp":"7564568208720527368"},"signature":{"hash":"jQaDJWQfhYrC6JXkCgd5qjmiucY=","keyId":{"high":1754143565,"low":2,"unsigned":false}}},"code":85,"codeName":"IndexOptionsConflict","errorLabelSet":{},"errorResponse":{"$clusterTime":{"clusterTime":{"$timestamp":"7564568208720527368"},"signature":{"hash":"jQaDJWQfhYrC6JXkCgd5qjmiucY=","keyId":{"high":1754143565,"low":2,"unsigned":false}}},"code":85,"codeName":"IndexOptionsConflict","errmsg":"Index already exists with a different name: conversationId_1_status_1","ok":0,"operationTime":{"$timestamp":"7564568208720527368"}},"level":"error","message":"❌ Erro ao criar índices: Index already exists with a different name: conversationId_1_status_1","ok":0,"operationTime":{"$timestamp":"7564568208720527368"},"service":"chat-api","stack":"MongoServerError: Index already exists with a different name: conversationId_1_status_1\n    at Connection.sendCommand (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\cmap\\connection.js:305:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Connection.command (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\cmap\\connection.js:333:26)\n    at async Server.command (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\sdam\\server.js:171:29)\n    at async CreateIndexesOperation.executeCommand (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\command.js:76:16)\n    at async CreateIndexesOperation.execute (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\indexes.js:122:9)\n    at async tryOperation (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:207:20)\n    at async executeOperation (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:75:16)\n    at async Collection.createIndex (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\collection.js:329:25)\n    at async addPerformanceIndexes (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\scripts\\add-performance-indexes.js:72:5)","timestamp":"2025-10-23 20:48:50"}
{"$clusterTime":{"clusterTime":{"$timestamp":"7564568586677649411"},"signature":{"hash":"EVYYiA/f/cry2ZguANNyZHiUJnI=","keyId":{"high":1754143565,"low":2,"unsigned":false}}},"code":85,"codeName":"IndexOptionsConflict","errorLabelSet":{},"errorResponse":{"$clusterTime":{"clusterTime":{"$timestamp":"7564568586677649411"},"signature":{"hash":"EVYYiA/f/cry2ZguANNyZHiUJnI=","keyId":{"high":1754143565,"low":2,"unsigned":false}}},"code":85,"codeName":"IndexOptionsConflict","errmsg":"Index already exists with a different name: conversationId_1_status_1","ok":0,"operationTime":{"$timestamp":"7564568586677649411"}},"level":"error","message":"❌ Erro ao criar índices: Index already exists with a different name: conversationId_1_status_1","ok":0,"operationTime":{"$timestamp":"7564568586677649411"},"service":"chat-api","stack":"MongoServerError: Index already exists with a different name: conversationId_1_status_1\n    at Connection.sendCommand (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\cmap\\connection.js:305:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Connection.command (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\cmap\\connection.js:333:26)\n    at async Server.command (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\sdam\\server.js:171:29)\n    at async CreateIndexesOperation.executeCommand (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\command.js:76:16)\n    at async CreateIndexesOperation.execute (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\indexes.js:122:9)\n    at async tryOperation (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:207:20)\n    at async executeOperation (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:75:16)\n    at async Collection.createIndex (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\node_modules\\mongodb\\lib\\collection.js:329:25)\n    at async addPerformanceIndexes (C:\\SandboxShare\\Nova pasta\\Nova pasta\\HackloteChatApi\\scripts\\add-performance-indexes.js:72:5)","timestamp":"2025-10-23 20:50:18"}
